Implemented components for company search bar
JobCompare/jc-client pull request #10
Opened 2017-06-09 05:52 UTC by bsoe003

* Created components and containers: `MainContainer`, `Overlay`, and `SearchEngine`
* Created a reducer: `SearchEngineReducer`
* Created `OverlayController` to access Overlay's core features across components
* Added [`PropTypes`](https://facebook.github.io/react/docs/typechecking-with-proptypes.html) to check types for React component props
* Added [`enzyme`](http://airbnb.io/enzyme/docs/api/) to write unit tests for React Components
* Wrote tests for: `Overlay`, `OverlayController`, `SearchEngine`, `SearchEngineReducer`, and `Switch`
* Allow webpack to import json
* Removed `ToolBox` and `ToolBoxReducer` that were used as references

2017-06-09 23:34 UTC, bsoe003 commented on app/components/containers/MainContainer.js
> +  <div id='main-container'>
will change to `<main>`

2017-07-04 21:08 UTC, timothyk7 requested changes
Quick explanation on the benefits of using prop-types and add to readme.  Everything else looks good.

2017-07-04 21:08 UTC, timothyk7 commented on app/components/Logo.js
> +import PropTypes from 'prop-types';
explain what this is in readme

2017-07-04 21:51 UTC, timothyk7 approved these changes

2017-07-04 21:51 UTC, merged